# -*- coding: utf-8 -*-
"""atividade_data_Science_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vlAxqxaXAk-4DvWjSe2DbBTMyhuu6UOo
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Carregando os dados
df = pd.read_csv('Indian_Kids_Screen_Time.csv')
df = df.dropna(subset=['Avg_Daily_Screen_Time_hr'])

# Histograma
sns.histplot(df['Avg_Daily_Screen_Time_hr'],bins=20, kde=False)
plt.title('Histograma do Tempo de Tela')
plt.xlabel('Horas de Tela')
plt.ylabel('Frequência')
plt.grid(True)
plt.show()

# Curva de densidade
sns.kdeplot(df['Avg_Daily_Screen_Time_hr'], shade=True)
plt.title('Curva de Densidade do Tempo de Tela')
plt.xlabel('Horas de Tela')
plt.grid(True)
plt.show()

# Boxplot com outliers
sns.boxplot(y=df['Avg_Daily_Screen_Time_hr'], showfliers=True)
plt.title('Boxplot com Outliers')
plt.ylabel('Horas de Tela')
plt.grid(True)
plt.show()


# Boxplot sem outliers
sns.boxplot(y=df['Avg_Daily_Screen_Time_hr'], showfliers=False)
plt.title('Boxplot sem Outliers')
plt.ylabel('Horas de Tela')
plt.grid(True)
plt.show()

df['Avg_Daily_Screen_Time_hr'].describe()

print(df.columns)